### ISSUE TITLE
bug theme Stream for Moodle

### ISSUE THREAD

**Issue by amoscom** [hribeir0/moodle-theme_stream#1]
link to "featured courses" not working
link to myserver/course in the place of  myserver/moodle/course

link to "featured categories" works but lik to myserver/moodle/course

Thank you

**Comment by hribeir0** [comment]
Thanks! You are correct. This will be fixed in the next version.
If you need to correct it now on your installation you can edit the language pack, namely the string "featuredcoursescopy". Instead of `With our online courses, you can learn anytime, anywhere, at your own pace. <a href="/course" >Explore them!</a>` the link should be `href="course/"`

I'm not sure if this is the best approach or if I will transform this text in a theme setting. Let me reflect on that.

Regards

**Comment by hribeir0** [comment]
The string was changed and while not a setting you can edit the string in the language editor. The link is now pointing at the correct URL
